insert into Cidade (id, nome, idPais) values (1, 'Abrantes', 184);
insert into Cidade (id, nome, idPais) values (2, 'Agualva-Cacém', 184);
insert into Cidade (id, nome, idPais) values (3, 'Águeda', 184);
insert into Cidade (id, nome, idPais) values (4, 'Albergaria-a-Velha', 184);
insert into Cidade (id, nome, idPais) values (5, 'Albufeira', 184);
insert into Cidade (id, nome, idPais) values (6, 'Alcácer do Sal', 184);
insert into Cidade (id, nome, idPais) values (7, 'Alcobaça', 184);
insert into Cidade (id, nome, idPais) values (8, 'Alfena', 184);
insert into Cidade (id, nome, idPais) values (9, 'Almada', 184);
insert into Cidade (id, nome, idPais) values (10, 'Almeirim', 184);
insert into Cidade (id, nome, idPais) values (11, 'Alverca do Ribatejo', 184);
insert into Cidade (id, nome, idPais) values (12, 'Amadora', 184);
insert into Cidade (id, nome, idPais) values (13, 'Amarante', 184);
insert into Cidade (id, nome, idPais) values (14, 'Amora', 184);
insert into Cidade (id, nome, idPais) values (15, 'Anadia', 184);
insert into Cidade (id, nome, idPais) values (16, 'Angra do Heroísmo', 184);
insert into Cidade (id, nome, idPais) values (17, 'Aveiro', 184);
insert into Cidade (id, nome, idPais) values (18, 'Barcelos', 184);
insert into Cidade (id, nome, idPais) values (19, 'Barreiro', 184);
insert into Cidade (id, nome, idPais) values (20, 'Beja', 184);
insert into Cidade (id, nome, idPais) values (21, 'Borba', 184);
insert into Cidade (id, nome, idPais) values (22, 'Braga', 184);
insert into Cidade (id, nome, idPais) values (23, 'Bragança', 184);
insert into Cidade (id, nome, idPais) values (24, 'Caldas da Rainha', 184);
insert into Cidade (id, nome, idPais) values (25, 'Câmara de Lobos', 184);
insert into Cidade (id, nome, idPais) values (26, 'Caniço', 184);
insert into Cidade (id, nome, idPais) values (27, 'Cantanhede', 184);
insert into Cidade (id, nome, idPais) values (28, 'Cartaxo', 184);
insert into Cidade (id, nome, idPais) values (29, 'Castelo Branco', 184);
insert into Cidade (id, nome, idPais) values (30, 'Chaves', 184);
insert into Cidade (id, nome, idPais) values (31, 'Coimbra', 184);
insert into Cidade (id, nome, idPais) values (32, 'Costa da Caparica', 184);
insert into Cidade (id, nome, idPais) values (33, 'Covilhã', 184);
insert into Cidade (id, nome, idPais) values (34, 'Elvas', 184);
insert into Cidade (id, nome, idPais) values (35, 'Entroncamento', 184);
insert into Cidade (id, nome, idPais) values (36, 'Ermesinde', 184);
insert into Cidade (id, nome, idPais) values (37, 'Esmoriz', 184);
insert into Cidade (id, nome, idPais) values (38, 'Espinho', 184);
insert into Cidade (id, nome, idPais) values (39, 'Esposende', 184);
insert into Cidade (id, nome, idPais) values (40, 'Estarreja', 184);
insert into Cidade (id, nome, idPais) values (41, 'Estremoz', 184);
insert into Cidade (id, nome, idPais) values (42, 'Évora', 184);
insert into Cidade (id, nome, idPais) values (43, 'Fafe', 184);
insert into Cidade (id, nome, idPais) values (44, 'Faro', 184);
insert into Cidade (id, nome, idPais) values (45, 'Fátima', 184);
insert into Cidade (id, nome, idPais) values (46, 'Felgueiras', 184);
insert into Cidade (id, nome, idPais) values (47, 'Figueira da Foz', 184);
insert into Cidade (id, nome, idPais) values (48, 'Fiães', 184);
insert into Cidade (id, nome, idPais) values (49, 'Freamunde', 184);
insert into Cidade (id, nome, idPais) values (50, 'Funchal', 184);
insert into Cidade (id, nome, idPais) values (51, 'Fundão', 184);
insert into Cidade (id, nome, idPais) values (52, 'Gafanha da Nazaré', 184);
insert into Cidade (id, nome, idPais) values (53, 'Gandra', 184);
insert into Cidade (id, nome, idPais) values (54, 'Gondomar', 184);
insert into Cidade (id, nome, idPais) values (55, 'Gouveia', 184);
insert into Cidade (id, nome, idPais) values (56, 'Guarda', 184);
insert into Cidade (id, nome, idPais) values (57, 'Guimarães', 184);
insert into Cidade (id, nome, idPais) values (58, 'Horta', 184);
insert into Cidade (id, nome, idPais) values (59, 'Ílhavo', 184);
insert into Cidade (id, nome, idPais) values (60, 'Lagoa', 184);
insert into Cidade (id, nome, idPais) values (61, 'Lagoa', 184);
insert into Cidade (id, nome, idPais) values (62, 'Lagos', 184);
insert into Cidade (id, nome, idPais) values (63, 'Lamego', 184);
insert into Cidade (id, nome, idPais) values (64, 'Leiria', 184);
insert into Cidade (id, nome, idPais) values (65, 'Lisboa', 184);
insert into Cidade (id, nome, idPais) values (66, 'Lixa', 184);
insert into Cidade (id, nome, idPais) values (67, 'Loulé', 184);
insert into Cidade (id, nome, idPais) values (68, 'Loures', 184);
insert into Cidade (id, nome, idPais) values (69, 'Lourosa', 184);
insert into Cidade (id, nome, idPais) values (70, 'Macedo de Cavaleiros', 184);
insert into Cidade (id, nome, idPais) values (71, 'Machico', 184);
insert into Cidade (id, nome, idPais) values (72, 'Maia', 184);
insert into Cidade (id, nome, idPais) values (73, 'Mangualde', 184);
insert into Cidade (id, nome, idPais) values (74, 'Marco de Canaveses', 184);
insert into Cidade (id, nome, idPais) values (75, 'Marinha Grande', 184);
insert into Cidade (id, nome, idPais) values (76, 'Matosinhos', 184);
insert into Cidade (id, nome, idPais) values (77, 'Mealhada', 184);
insert into Cidade (id, nome, idPais) values (78, 'Mêda', 184);
insert into Cidade (id, nome, idPais) values (79, 'Miranda do Douro / Miranda de l Douro', 184);
insert into Cidade (id, nome, idPais) values (80, 'Mirandela', 184);
insert into Cidade (id, nome, idPais) values (81, 'Montemor-o-Novo', 184);
insert into Cidade (id, nome, idPais) values (82, 'Montijo', 184);
insert into Cidade (id, nome, idPais) values (83, 'Moura', 184);
insert into Cidade (id, nome, idPais) values (84, 'Odivelas', 184);
insert into Cidade (id, nome, idPais) values (85, 'Olhão da Restauração', 184);
insert into Cidade (id, nome, idPais) values (86, 'Oliveira de Azeméis', 184);
insert into Cidade (id, nome, idPais) values (87, 'Oliveira do Bairro', 184);
insert into Cidade (id, nome, idPais) values (88, 'Oliveira do Hospital', 184);
insert into Cidade (id, nome, idPais) values (89, 'Ourém', 184);
insert into Cidade (id, nome, idPais) values (90, 'Ovar', 184);
insert into Cidade (id, nome, idPais) values (91, 'Paços de Ferreira', 184);
insert into Cidade (id, nome, idPais) values (92, 'Paredes', 184);
insert into Cidade (id, nome, idPais) values (93, 'Penafiel', 184);
insert into Cidade (id, nome, idPais) values (94, 'Peniche', 184);
insert into Cidade (id, nome, idPais) values (95, 'Peso da Régua', 184);
insert into Cidade (id, nome, idPais) values (96, 'Pinhel', 184);
insert into Cidade (id, nome, idPais) values (97, 'Pombal', 184);
insert into Cidade (id, nome, idPais) values (98, 'Ponta Delgada', 184);
insert into Cidade (id, nome, idPais) values (99, 'Ponte de Sor', 184);
insert into Cidade (id, nome, idPais) values (100, 'Portalegre', 184);
insert into Cidade (id, nome, idPais) values (101, 'Portimão', 184);
insert into Cidade (id, nome, idPais) values (102, 'Porto', 184);
insert into Cidade (id, nome, idPais) values (103, 'Póvoa de Santa Iria', 184);
insert into Cidade (id, nome, idPais) values (104, 'Póvoa de Varzim', 184);
insert into Cidade (id, nome, idPais) values (105, 'Praia da Vitória', 184);
insert into Cidade (id, nome, idPais) values (106, 'Quarteira', 184);
insert into Cidade (id, nome, idPais) values (107, 'Queluz', 184);
insert into Cidade (id, nome, idPais) values (108, 'Rebordosa', 184);
insert into Cidade (id, nome, idPais) values (109, 'Reguengos de Monsaraz', 184);
insert into Cidade (id, nome, idPais) values (110, 'Ribeira Grande', 184);
insert into Cidade (id, nome, idPais) values (111, 'Rio maior', 184);
insert into Cidade (id, nome, idPais) values (112, 'Rio Tinto', 184);
insert into Cidade (id, nome, idPais) values (113, 'Sabugal', 184);
insert into Cidade (id, nome, idPais) values (114, 'Sacavém', 184);
insert into Cidade (id, nome, idPais) values (115, 'Samora Correia', 184);
insert into Cidade (id, nome, idPais) values (116, 'Santa Comba Dão', 184);
insert into Cidade (id, nome, idPais) values (117, 'Santa Cruz', 184);
insert into Cidade (id, nome, idPais) values (118, 'Santa Maria da Feira', 184);
insert into Cidade (id, nome, idPais) values (119, 'Santana', 184);
insert into Cidade (id, nome, idPais) values (120, 'Santarém', 184);
insert into Cidade (id, nome, idPais) values (121, 'Santiago do Cacém', 184);
insert into Cidade (id, nome, idPais) values (122, 'Santo Tirso', 184);
insert into Cidade (id, nome, idPais) values (123, 'São João da Madeira', 184);
insert into Cidade (id, nome, idPais) values (124, 'São Mamede de Infesta', 184);
insert into Cidade (id, nome, idPais) values (125, 'São Pedro do Sul', 184);
insert into Cidade (id, nome, idPais) values (126, 'São Salvador de Lordelo', 184);
insert into Cidade (id, nome, idPais) values (127, 'Seia', 184);
insert into Cidade (id, nome, idPais) values (128, 'Seixal', 184);
insert into Cidade (id, nome, idPais) values (129, 'Senhora da Hora', 184);
insert into Cidade (id, nome, idPais) values (130, 'Serpa', 184);
insert into Cidade (id, nome, idPais) values (131, 'Setúbal', 184);
insert into Cidade (id, nome, idPais) values (132, 'Silves', 184);
insert into Cidade (id, nome, idPais) values (133, 'Sines', 184);
insert into Cidade (id, nome, idPais) values (134, 'Tarouca', 184);
insert into Cidade (id, nome, idPais) values (135, 'Tavira', 184);
insert into Cidade (id, nome, idPais) values (136, 'Tomar', 184);
insert into Cidade (id, nome, idPais) values (137, 'Tondela', 184);
insert into Cidade (id, nome, idPais) values (138, 'Torres Novas', 184);
insert into Cidade (id, nome, idPais) values (139, 'Torres Vedras', 184);
insert into Cidade (id, nome, idPais) values (140, 'Trancoso', 184);
insert into Cidade (id, nome, idPais) values (141, 'Trofa', 184);
insert into Cidade (id, nome, idPais) values (142, 'Valbom', 184);
insert into Cidade (id, nome, idPais) values (143, 'Vale de Cambra', 184);
insert into Cidade (id, nome, idPais) values (144, 'Valença', 184);
insert into Cidade (id, nome, idPais) values (145, 'Valongo', 184);
insert into Cidade (id, nome, idPais) values (146, 'Valpaços', 184);
insert into Cidade (id, nome, idPais) values (147, 'Vendas Novas', 184);
insert into Cidade (id, nome, idPais) values (148, 'Viana do Castelo', 184);
insert into Cidade (id, nome, idPais) values (149, 'Vila Baleira', 184);
insert into Cidade (id, nome, idPais) values (150, 'Vila do Conde', 184);
insert into Cidade (id, nome, idPais) values (151, 'Vila Franca de Xira', 184);
insert into Cidade (id, nome, idPais) values (152, 'Vila Nova de Famalicão', 184);
insert into Cidade (id, nome, idPais) values (153, 'Vila Nova de Foz Côa', 184);
insert into Cidade (id, nome, idPais) values (154, 'Vila Nova de Gaia', 184);
insert into Cidade (id, nome, idPais) values (155, 'Vila Nova de Santo André', 184);
insert into Cidade (id, nome, idPais) values (156, 'Vila Real', 184);
insert into Cidade (id, nome, idPais) values (157, 'Vila Real de Santo António', 184);
insert into Cidade (id, nome, idPais) values (158, 'Viseu', 184);
insert into Cidade (id, nome, idPais) values (159, 'Vizela', 184);


insert into Cidade (id, nome, idPais) values (160, 'Shanghai', 48);
  insert into Cidade (id, nome, idPais) values (161, 'Lagos', 164);
  insert into Cidade (id, nome, idPais) values (162, 'Istanbul', 225);
  insert into Cidade (id, nome, idPais) values (163, 'Karachi', 178);
  insert into Cidade (id, nome, idPais) values (164, 'Mumbai', 105);
  insert into Cidade (id, nome, idPais) values (165, 'Moscow', 191);
  insert into Cidade (id, nome, idPais) values (166, 'São Paulo', 31);
  insert into Cidade (id, nome, idPais) values (167, 'Beijing', 48);
  insert into Cidade (id, nome, idPais) values (168, 'Guangzhou', 48);
  insert into Cidade (id, nome, idPais) values (169, 'Delhi', 105);
  insert into Cidade (id, nome, idPais) values (170, 'Lahore', 178);
  insert into Cidade (id, nome, idPais) values (171, 'Shenzhen', 48);
  insert into Cidade (id, nome, idPais) values (172, 'Seoul', 122);
  insert into Cidade (id, nome, idPais) values (173, 'Jakarta', 101);
  insert into Cidade (id, nome, idPais) values (174, 'Tianjin', 48);
  insert into Cidade (id, nome, idPais) values (175, 'Chennai', 105);
  insert into Cidade (id, nome, idPais) values (176, 'Tokyo', 114);
  insert into Cidade (id, nome, idPais) values (177, 'Cairo', 65);
  insert into Cidade (id, nome, idPais) values (178, 'Dhaka', 19);
  insert into Cidade (id, nome, idPais) values (179, 'Mexico City', 157);
  insert into Cidade (id, nome, idPais) values (180, 'Kinshasa', 40);
  insert into Cidade (id, nome, idPais) values (181, 'Bangalore', 105);
  insert into Cidade (id, nome, idPais) values (182, 'New York', 233);
  insert into Cidade (id, nome, idPais) values (183, 'London', 77);
  insert into Cidade (id, nome, idPais) values (184, 'Bangkok', 218);
  insert into Cidade (id, nome, idPais) values (185, 'Tehran', 108);
  insert into Cidade (id, nome, idPais) values (186, 'Dongguan', 48);
  insert into Cidade (id, nome, idPais) values (187, 'Ho Chi Minh City', 241);
  insert into Cidade (id, nome, idPais) values (188, 'Bogotá', 49);
  insert into Cidade (id, nome, idPais) values (189, 'Lima', 174);
  insert into Cidade (id, nome, idPais) values (190, 'Hong Kong', 95);
  insert into Cidade (id, nome, idPais) values (191, 'Hanoi', 241);
  insert into Cidade (id, nome, idPais) values (192, 'Hyderabad', 105);
  insert into Cidade (id, nome, idPais) values (193, 'Wuhan', 48);
  insert into Cidade (id, nome, idPais) values (194, 'Rio de Janeiro', 31);
  insert into Cidade (id, nome, idPais) values (195, 'Foshan', 48);
  insert into Cidade (id, nome, idPais) values (196, 'Ahmedabad', 105);
  insert into Cidade (id, nome, idPais) values (197, 'Baghdad', 107);
  insert into Cidade (id, nome, idPais) values (198, 'Singapore', 198);
  insert into Cidade (id, nome, idPais) values (199, 'Shantou', 48);
  insert into Cidade (id, nome, idPais) values (200, 'Riyadh', 193);
  insert into Cidade (id, nome, idPais) values (201, 'Jeddah', 193);
  insert into Cidade (id, nome, idPais) values (202, 'Santiago', 46);
  insert into Cidade (id, nome, idPais) values (203, 'Saint Petersburg', 191);
  insert into Cidade (id, nome, idPais) values (204, 'Qalyubia', 65);
  insert into Cidade (id, nome, idPais) values (205, 'Chengdu', 48);
  insert into Cidade (id, nome, idPais) values (206, 'Alexandria', 65);
  insert into Cidade (id, nome, idPais) values (207, 'Ankara', 225);
  insert into Cidade (id, nome, idPais) values (208, 'Chongqing', 48);
  insert into Cidade (id, nome, idPais) values (209, 'Kolkata', 105);
  insert into Cidade (id, nome, idPais) values (210, 'Xi''an', 48);
  insert into Cidade (id, nome, idPais) values (211, 'Surat', 105);
  insert into Cidade (id, nome, idPais) values (212, 'Johannesburg', 247);
  insert into Cidade (id, nome, idPais) values (213, 'Nanjing', 48);
  insert into Cidade (id, nome, idPais) values (214, 'Dar es Salaam', 229);
  insert into Cidade (id, nome, idPais) values (215, 'Yangon', 48);
  insert into Cidade (id, nome, idPais) values (216, 'Abidjan', 44);
  insert into Cidade (id, nome, idPais) values (217, 'Harbin', 48);
  insert into Cidade (id, nome, idPais) values (218, 'Zhengzhou', 48);
  insert into Cidade (id, nome, idPais) values (219, 'Suzhou', 48);
  insert into Cidade (id, nome, idPais) values (220, 'Sydney', 13);
  insert into Cidade (id, nome, idPais) values (221, 'New Taipei City', 228);
  insert into Cidade (id, nome, idPais) values (222, 'Los Angeles', 233);
  insert into Cidade (id, nome, idPais) values (223, 'Melbourne', 13);
  insert into Cidade (id, nome, idPais) values (224, 'Cape Town', 247);
  insert into Cidade (id, nome, idPais) values (225, 'Shenyang', 48);
  insert into Cidade (id, nome, idPais) values (226, 'Yokohama', 114);
  insert into Cidade (id, nome, idPais) values (227, 'Busan', 122);
  insert into Cidade (id, nome, idPais) values (228, 'Hangzhou', 48);
  insert into Cidade (id, nome, idPais) values (229, 'Quanzhou', 48);
  insert into Cidade (id, nome, idPais) values (230, 'Durban', 247);
  insert into Cidade (id, nome, idPais) values (231, 'Casablanca', 137);
  insert into Cidade (id, nome, idPais) values (232, 'Algiers', 62);
  insert into Cidade (id, nome, idPais) values (233, 'Berlin', 57);
  insert into Cidade (id, nome, idPais) values (234, 'Nairobi', 115);
  insert into Cidade (id, nome, idPais) values (235, 'Hefei', 48);
  insert into Cidade (id, nome, idPais) values (236, 'Kabul', 3);
  insert into Cidade (id, nome, idPais) values (237, 'Pyongyang', 121);
  insert into Cidade (id, nome, idPais) values (238, 'Madrid', 68);
  insert into Cidade (id, nome, idPais) values (239, 'Ekurhuleni', 247);
  insert into Cidade (id, nome, idPais) values (240, 'Pune', 105);
  insert into Cidade (id, nome, idPais) values (241, 'Addis Ababa', 69);
  insert into Cidade (id, nome, idPais) values (242, 'Changsha', 48);
  insert into Cidade (id, nome, idPais) values (243, 'Jaipur', 105);
  insert into Cidade (id, nome, idPais) values (244, 'Xuzhou', 48);
  insert into Cidade (id, nome, idPais) values (245, 'Wenzhou', 48);
