insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (415, 1, 1, 'Treinador Principal');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (416, 2, 2, 'Treinador Principal');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (417, 3, 3, 'Treinador Principal');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (418, 4, 4, 'Treinador Principal');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (419, 5, 5, 'Treinador Principal');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (420, 6, 6, 'Treinador Principal');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (421, 7, 7, 'Treinador Principal');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (422, 8, 8, 'Treinador Principal');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (423, 9, 9, 'Treinador Principal');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (424, 10, 10, 'Treinador Principal');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (425, 11, 11, 'Treinador Principal');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (426, 12, 12, 'Treinador Principal');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (427, 13, 13, 'Treinador Principal');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (428, 14, 14, 'Treinador Principal');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (429, 15, 15, 'Treinador Principal');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (430, 16, 16, 'Treinador Principal');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (431, 17, 17, 'Treinador Principal');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (432, 18, 18, 'Treinador Principal');

  insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (433, 19, 1, 'Treinador-Adjunto');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (434, 20, 2, 'Treinador-Adjunto');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (435, 21, 3, 'Treinador-Adjunto');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (436, 22, 4, 'Treinador-Adjunto');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (437, 23, 5, 'Treinador-Adjunto');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (438, 24, 6, 'Treinador-Adjunto');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (439, 25, 7, 'Treinador-Adjunto');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (440, 26, 8, 'Treinador-Adjunto');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (441, 27, 9, 'Treinador-Adjunto');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (442, 28, 10, 'Treinador-Adjunto');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (443, 29, 11, 'Treinador-Adjunto');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (444, 30, 12, 'Treinador-Adjunto');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (445, 31, 13, 'Treinador-Adjunto');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (446, 32, 14, 'Treinador-Adjunto');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (447, 33, 15, 'Treinador-Adjunto');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (448, 34, 16, 'Treinador-Adjunto');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (449, 35, 17, 'Treinador-Adjunto');
insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (450, 36, 18, 'Treinador-Adjunto');

  insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (451, 37, 1, 'Preparador Físico');
  insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (452, 38, 2, 'Preparador Físico');
  insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (453, 39, 3, 'Preparador Físico');
  insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (454, 40, 4, 'Preparador Físico');
  insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (455, 41, 5, 'Preparador Físico');
  insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (456, 42, 6, 'Preparador Físico');
  insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (457, 43, 7, 'Preparador Físico');
  insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (458, 44, 8, 'Preparador Físico');
  insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (459, 45, 9, 'Preparador Físico');
  insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (460, 46, 10, 'Preparador Físico');
  insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (461, 47, 11, 'Preparador Físico');
  insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (462, 48, 12, 'Preparador Físico');
  insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (463, 49, 13, 'Preparador Físico');
  insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (464, 50, 14, 'Preparador Físico');
  insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (465, 51, 15, 'Preparador Físico');
  insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (466, 52, 16, 'Preparador Físico');
  insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (467, 53, 17, 'Preparador Físico');
  insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (468, 54, 18, 'Preparador Físico');

    insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (469, 55, 1, 'Massagista');
    insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (470, 56, 2, 'Massagista');
    insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (471, 57, 3, 'Massagista');
    insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (472, 58, 4, 'Massagista');
    insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (473, 59, 5, 'Massagista');
    insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (474, 60, 6, 'Massagista');
    insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (475, 61, 7, 'Massagista');
    insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (476, 62, 8, 'Massagista');
    insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (477, 63, 9, 'Massagista');
    insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (478, 64, 10, 'Massagista');
    insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (479, 65, 11, 'Massagista');
    insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (480, 66, 12, 'Massagista');
    insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (481, 67, 13, 'Massagista');
    insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (482, 68, 14, 'Massagista');
    insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (483, 69, 15, 'Massagista');
    insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (484, 70, 16, 'Massagista');
    insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (485, 71, 17, 'Massagista');
    insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (486, 72, 18, 'Massagista');

      insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (487, 73, 1, 'Roupeiro');
      insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (488, 74, 2, 'Roupeiro');
      insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (489, 75, 3, 'Roupeiro');
      insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (490, 76, 4, 'Roupeiro');
      insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (491, 77, 5, 'Roupeiro');
      insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (492, 78, 6, 'Roupeiro');
      insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (493, 79, 7, 'Roupeiro');
      insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (494, 80, 8, 'Roupeiro');
      insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (495, 81, 9, 'Roupeiro');
      insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (496, 82, 10, 'Roupeiro');
      insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (497, 83, 11, 'Roupeiro');
      insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (498, 84, 12, 'Roupeiro');
      insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (499, 85, 13, 'Roupeiro');
      insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (500, 86, 14, 'Roupeiro');
      insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (501, 87, 15, 'Roupeiro');
      insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (502, 88, 16, 'Roupeiro');
      insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (503, 89, 17, 'Roupeiro');
      insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (504, 90, 18, 'Roupeiro');

        insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (505, 91, 1, 'Agueiro');
        insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (506, 92, 2, 'Agueiro');
        insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (507, 93, 3, 'Agueiro');
        insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (508, 94, 4, 'Agueiro');
        insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (509, 95, 5, 'Agueiro');
        insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (510, 96, 6, 'Agueiro');
        insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (511, 97, 7, 'Agueiro');
        insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (512, 98, 8, 'Agueiro');
        insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (513, 99, 9, 'Agueiro');
        insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (514, 100, 10, 'Agueiro');
        insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (515, 101, 11, 'Agueiro');
        insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (516, 102, 12, 'Agueiro');
        insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (517, 103, 13, 'Agueiro');
        insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (518, 104, 14, 'Agueiro');
        insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (519, 105, 15, 'Agueiro');
        insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (520, 106, 16, 'Agueiro');
        insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (521, 107, 17, 'Agueiro');
        insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (522, 108, 18, 'Agueiro');

          insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (523, 109, 1, 'Diretor');
          insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (524, 110, 2, 'Diretor');
          insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (525, 111, 3, 'Diretor');
          insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (526, 112, 4, 'Diretor');
          insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (527, 113, 5, 'Diretor');
          insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (528, 114, 6, 'Diretor');
          insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (529, 115, 7, 'Diretor');
          insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (530, 116, 8, 'Diretor');
          insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (531, 117, 9, 'Diretor');
          insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (532, 118, 10, 'Diretor');
          insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (533, 119, 11, 'Diretor');
          insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (534, 120, 12, 'Diretor');
          insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (535, 121, 13, 'Diretor');
          insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (536, 122, 14, 'Diretor');
          insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (537, 123, 15, 'Diretor');
          insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (538, 124, 16, 'Diretor');
          insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (539, 125, 17, 'Diretor');
          insert into ContratoStaff (idContrato, idStaff, idEquipa, idFuncao) values (540, 126, 18, 'Diretor');
