insert into Jogador (idPessoa, posicaoPref, pePref) values (1, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (2, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (3, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (4, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (5, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (6, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (7, 'Médio Defensivo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (8, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (9, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (10, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (11, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (12, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (13, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (14, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (15, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (16, 'Defesa Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (17, 'Médio Defensivo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (18, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (19, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (20, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (21, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (22, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (23, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (24, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (25, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (26, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (27, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (28, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (29, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (30, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (31, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (32, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (33, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (34, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (35, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (36, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (37, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (38, 'Médio Defensivo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (39, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (40, 'Médio Centro', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (41, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (42, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (43, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (44, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (45, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (46, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (47, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (48, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (49, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (50, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (51, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (52, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (53, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (54, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (55, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (56, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (57, 'Defesa Central', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (58, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (59, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (60, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (61, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (62, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (63, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (64, 'Médio Centro', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (65, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (66, 'Médio Centro', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (67, 'Médio Centro', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (68, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (69, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (70, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (71, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (72, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (73, 'Defesa Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (74, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (75, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (76, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (77, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (78, 'Médio Defensivo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (79, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (80, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (81, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (82, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (83, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (84, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (85, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (86, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (87, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (88, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (89, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (90, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (91, 'Médio Centro', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (92, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (93, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (94, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (95, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (96, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (97, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (98, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (99, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (100, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (101, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (102, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (103, 'Defesa Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (104, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (105, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (106, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (107, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (108, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (109, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (110, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (111, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (112, 'Médio Centro', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (113, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (114, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (115, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (116, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (117, 'Médio Centro', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (118, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (119, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (120, 'Médio Centro', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (121, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (122, 'Médio Centro', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (123, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (124, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (125, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (126, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (127, 'Defesa Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (128, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (129, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (130, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (131, 'Médio Centro', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (132, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (133, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (134, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (135, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (136, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (137, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (138, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (139, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (140, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (141, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (142, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (143, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (144, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (145, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (146, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (147, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (148, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (149, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (150, 'Médio Centro', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (151, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (152, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (153, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (154, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (155, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (156, 'Defesa Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (157, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (158, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (159, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (160, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (161, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (162, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (163, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (164, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (165, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (166, 'Médio Defensivo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (167, 'Médio Centro', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (168, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (169, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (170, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (171, 'Médio Centro', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (172, 'Defesa Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (173, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (174, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (175, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (176, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (177, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (178, 'Médio Defensivo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (179, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (180, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (181, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (182, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (183, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (184, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (185, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (186, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (187, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (188, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (189, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (190, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (191, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (192, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (193, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (194, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (195, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (196, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (197, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (198, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (199, 'Médio Centro', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (200, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (201, 'Médio Centro', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (202, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (203, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (204, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (205, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (206, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (207, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (208, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (209, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (210, 'Médio Centro', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (211, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (212, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (213, 'Médio Centro', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (214, 'Médio Defensivo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (215, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (216, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (217, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (218, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (219, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (220, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (221, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (222, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (223, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (224, 'Defesa Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (225, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (226, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (227, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (228, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (229, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (230, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (231, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (232, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (233, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (234, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (235, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (236, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (237, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (238, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (239, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (240, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (241, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (242, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (243, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (244, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (245, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (246, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (247, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (248, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (249, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (250, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (251, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (252, 'Médio Centro', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (253, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (254, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (255, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (256, 'Médio Centro', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (257, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (258, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (259, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (260, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (261, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (262, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (263, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (264, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (265, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (266, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (267, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (268, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (269, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (270, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (271, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (272, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (273, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (274, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (275, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (276, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (277, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (278, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (279, 'Médio Defensivo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (280, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (281, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (282, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (283, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (284, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (285, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (286, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (287, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (288, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (289, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (290, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (291, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (292, 'Médio Centro', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (293, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (294, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (295, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (296, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (297, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (298, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (299, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (300, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (301, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (302, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (303, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (304, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (305, 'Médio Centro', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (306, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (307, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (308, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (309, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (310, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (311, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (312, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (313, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (314, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (315, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (316, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (317, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (318, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (319, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (320, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (321, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (322, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (323, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (324, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (325, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (326, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (327, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (328, 'Médio Centro', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (329, 'Médio Centro', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (330, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (331, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (332, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (333, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (334, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (335, 'Médio Centro', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (336, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (337, 'Médio Centro', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (338, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (339, 'Defesa Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (340, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (341, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (342, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (343, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (344, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (345, 'Médio Defensivo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (346, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (347, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (348, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (349, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (350, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (351, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (352, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (353, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (354, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (355, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (356, 'Médio Centro', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (357, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (358, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (359, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (360, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (361, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (362, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (363, 'Médio Centro', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (364, 'Médio Centro', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (365, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (366, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (367, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (368, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (369, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (370, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (371, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (372, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (373, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (374, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (375, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (376, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (377, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (378, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (379, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (380, 'Médio Defensivo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (381, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (382, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (383, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (384, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (385, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (386, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (387, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (388, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (389, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (390, 'Defesa Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (391, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (392, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (393, 'Defesa Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (394, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (395, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (396, 'Defesa Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (397, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (398, 'Extremo Direito', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (399, 'Ponta de Lança', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (400, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (401, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (402, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (403, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (404, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (405, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (406, 'Extremo Esquerdo', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (407, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (408, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (409, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (410, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (411, 'Extremo Esquerdo', 'Esquerdo');
insert into Jogador (idPessoa, posicaoPref, pePref) values (412, 'Ponta de Lança', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (413, 'Extremo Direito', 'Direito');
insert into Jogador (idPessoa, posicaoPref, pePref) values (414, 'Médio Centro', 'Direito');
