insert into Pais (id, nome) values (1, 'Andorra');
insert into Pais (id, nome) values (2, 'United Arab Emirates');
insert into Pais (id, nome) values (3, 'Afghanistan');
insert into Pais (id, nome) values (4, 'Antigua and Barbuda');
insert into Pais (id, nome) values (5, 'Anguilla');
insert into Pais (id, nome) values (6, 'Albania');
insert into Pais (id, nome) values (7, 'Armenia');
insert into Pais (id, nome) values (8, 'Angola');
insert into Pais (id, nome) values (9, 'Antarctica');
insert into Pais (id, nome) values (10, 'Argentina');
insert into Pais (id, nome) values (11, 'American Samoa');
insert into Pais (id, nome) values (12, 'Austria');
insert into Pais (id, nome) values (13, 'Australia');
insert into Pais (id, nome) values (14, 'Aruba');
insert into Pais (id, nome) values (15, 'Åland Islands');
insert into Pais (id, nome) values (16, 'Azerbaijan');
insert into Pais (id, nome) values (17, 'Bosnia and Herzegovina');
insert into Pais (id, nome) values (18, 'Barbados');
insert into Pais (id, nome) values (19, 'Bangladesh');
insert into Pais (id, nome) values (20, 'Belgium');
insert into Pais (id, nome) values (21, 'Burkina Faso');
insert into Pais (id, nome) values (22, 'Bulgaria');
insert into Pais (id, nome) values (23, 'Bahrain');
insert into Pais (id, nome) values (24, 'Burundi');
insert into Pais (id, nome) values (25, 'Benin');
insert into Pais (id, nome) values (26, 'Saint Barthélemy');
insert into Pais (id, nome) values (27, 'Bermuda');
insert into Pais (id, nome) values (28, 'Brunei Darussalam');
insert into Pais (id, nome) values (29, 'Bolivia');
insert into Pais (id, nome) values (30, 'Caribbean Netherlands ');
insert into Pais (id, nome) values (31, 'Brazil');
insert into Pais (id, nome) values (32, 'Bahamas');
insert into Pais (id, nome) values (33, 'Bhutan');
insert into Pais (id, nome) values (34, 'Bouvet Island');
insert into Pais (id, nome) values (35, 'Botswana');
insert into Pais (id, nome) values (36, 'Belarus');
insert into Pais (id, nome) values (37, 'Belize');
insert into Pais (id, nome) values (38, 'Canada');
insert into Pais (id, nome) values (39, 'Cocos (Keeling) Islands');
insert into Pais (id, nome) values (40, 'Democratic Republic of Congo');
insert into Pais (id, nome) values (41, 'Central African Republic');
insert into Pais (id, nome) values (42, 'Congo');
insert into Pais (id, nome) values (43, 'Switzerland');
insert into Pais (id, nome) values (44, 'Côte d''Ivoire');
insert into Pais (id, nome) values (45, 'Cook Islands');
insert into Pais (id, nome) values (46, 'Chile');
insert into Pais (id, nome) values (47, 'Cameroon');
insert into Pais (id, nome) values (48, 'China');
insert into Pais (id, nome) values (49, 'Colombia');
insert into Pais (id, nome) values (50, 'Costa Rica');
insert into Pais (id, nome) values (51, 'Cuba');
insert into Pais (id, nome) values (52, 'Cape Verde');
insert into Pais (id, nome) values (53, 'Curaçao');
insert into Pais (id, nome) values (54, 'Christmas Island');
insert into Pais (id, nome) values (55, 'Cyprus');
insert into Pais (id, nome) values (56, 'Czech Republic');
insert into Pais (id, nome) values (57, 'Germany');
insert into Pais (id, nome) values (58, 'Djibouti');
insert into Pais (id, nome) values (59, 'Denmark');
insert into Pais (id, nome) values (60, 'Dominica');
insert into Pais (id, nome) values (61, 'Dominican Republic');
insert into Pais (id, nome) values (62, 'Algeria');
insert into Pais (id, nome) values (63, 'Ecuador');
insert into Pais (id, nome) values (64, 'Estonia');
insert into Pais (id, nome) values (65, 'Egypt');
insert into Pais (id, nome) values (66, 'Western Sahara');
insert into Pais (id, nome) values (67, 'Eritrea');
insert into Pais (id, nome) values (68, 'Spain');
insert into Pais (id, nome) values (69, 'Ethiopia');
insert into Pais (id, nome) values (70, 'Finland');
insert into Pais (id, nome) values (71, 'Fiji');
insert into Pais (id, nome) values (72, 'Falkland Islands');
insert into Pais (id, nome) values (73, ' Federated States of Micronesia');
insert into Pais (id, nome) values (74, 'Faroe Islands');
insert into Pais (id, nome) values (75, 'France');
insert into Pais (id, nome) values (76, 'Gabon');
insert into Pais (id, nome) values (77, 'United Kingdom');
insert into Pais (id, nome) values (78, 'Grenada');
insert into Pais (id, nome) values (79, 'Georgia');
insert into Pais (id, nome) values (80, 'French Guiana');
insert into Pais (id, nome) values (81, 'Guernsey');
insert into Pais (id, nome) values (82, 'Ghana');
insert into Pais (id, nome) values (83, 'Gibraltar');
insert into Pais (id, nome) values (84, 'Greenland');
insert into Pais (id, nome) values (85, 'Gambia');
insert into Pais (id, nome) values (86, 'Guinea');
insert into Pais (id, nome) values (87, 'Guadeloupe');
insert into Pais (id, nome) values (88, 'Equatorial Guinea');
insert into Pais (id, nome) values (89, 'Greece');
insert into Pais (id, nome) values (90, 'South Georgia and the South Sandwich Islands');
insert into Pais (id, nome) values (91, 'Guatemala');
insert into Pais (id, nome) values (92, 'Guam');
insert into Pais (id, nome) values (93, 'Guinea-Bissau');
insert into Pais (id, nome) values (94, 'Guyana');
insert into Pais (id, nome) values (95, 'Hong Kong');
insert into Pais (id, nome) values (96, 'Heard and McDonald Islands');
insert into Pais (id, nome) values (97, 'Honduras');
insert into Pais (id, nome) values (98, 'Croatia');
insert into Pais (id, nome) values (99, 'Haiti');
insert into Pais (id, nome) values (100, 'Hungary');
insert into Pais (id, nome) values (101, 'Indonesia');
insert into Pais (id, nome) values (102, 'Ireland');
insert into Pais (id, nome) values (103, 'Israel');
insert into Pais (id, nome) values (104, 'Isle of Man');
insert into Pais (id, nome) values (105, 'India');
insert into Pais (id, nome) values (106, 'British Indian Ocean Territory');
insert into Pais (id, nome) values (107, 'Iraq');
insert into Pais (id, nome) values (108, 'Iran');
insert into Pais (id, nome) values (109, 'Iceland');
insert into Pais (id, nome) values (110, 'Italy');
insert into Pais (id, nome) values (111, 'Jersey');
insert into Pais (id, nome) values (112, 'Jamaica');
insert into Pais (id, nome) values (113, 'Jordan');
insert into Pais (id, nome) values (114, 'Japan');
insert into Pais (id, nome) values (115, 'Kenya');
insert into Pais (id, nome) values (116, 'Kyrgyzstan');
insert into Pais (id, nome) values (117, 'Cambodia');
insert into Pais (id, nome) values (118, 'Kiribati');
insert into Pais (id, nome) values (119, 'Comoros');
insert into Pais (id, nome) values (120, 'Saint Kitts and Nevis');
insert into Pais (id, nome) values (121, 'North Korea');
insert into Pais (id, nome) values (122, 'South Korea');
insert into Pais (id, nome) values (123, 'Kuwait');
insert into Pais (id, nome) values (124, 'Cayman Islands');
insert into Pais (id, nome) values (125, 'Kazakhstan');
insert into Pais (id, nome) values (126, 'Lao People''s Democratic Republic');
insert into Pais (id, nome) values (127, 'Lebanon');
insert into Pais (id, nome) values (128, 'Saint Lucia');
insert into Pais (id, nome) values (129, 'Liechtenstein');
insert into Pais (id, nome) values (130, 'Sri Lanka');
insert into Pais (id, nome) values (131, 'Liberia');
insert into Pais (id, nome) values (132, 'Lesotho');
insert into Pais (id, nome) values (133, 'Lithuania');
insert into Pais (id, nome) values (134, 'Luxembourg');
insert into Pais (id, nome) values (135, 'Latvia');
insert into Pais (id, nome) values (136, 'Libya');
insert into Pais (id, nome) values (137, 'Morocco');
insert into Pais (id, nome) values (138, 'Monaco');
insert into Pais (id, nome) values (139, 'Moldova');
insert into Pais (id, nome) values (140, 'Montenegro');
insert into Pais (id, nome) values (141, 'Saint-Martin (France)');
insert into Pais (id, nome) values (142, 'Madagascar');
insert into Pais (id, nome) values (143, 'Marshall Islands');
insert into Pais (id, nome) values (144, 'Macedonia');
insert into Pais (id, nome) values (145, 'Mali');
insert into Pais (id, nome) values (146, 'Myanmar');
insert into Pais (id, nome) values (147, 'Mongolia');
insert into Pais (id, nome) values (148, 'Macau');
insert into Pais (id, nome) values (149, 'Northern Mariana Islands');
insert into Pais (id, nome) values (150, 'Martinique');
insert into Pais (id, nome) values (151, 'Mauritania');
insert into Pais (id, nome) values (152, 'Montserrat');
insert into Pais (id, nome) values (153, 'Malta');
insert into Pais (id, nome) values (154, 'Mauritius');
insert into Pais (id, nome) values (155, 'Maldives');
insert into Pais (id, nome) values (156, 'Malawi');
insert into Pais (id, nome) values (157, 'Mexico');
insert into Pais (id, nome) values (158, 'Malaysia');
insert into Pais (id, nome) values (159, 'Mozambique');
insert into Pais (id, nome) values (160, 'Namibia');
insert into Pais (id, nome) values (161, 'New Caledonia');
insert into Pais (id, nome) values (162, 'Niger');
insert into Pais (id, nome) values (163, 'Norfolk Island');
insert into Pais (id, nome) values (164, 'Nigeria');
insert into Pais (id, nome) values (165, 'Nicaragua');
insert into Pais (id, nome) values (166, 'The Netherlands');
insert into Pais (id, nome) values (167, 'Norway');
insert into Pais (id, nome) values (168, 'Nepal');
insert into Pais (id, nome) values (169, 'Nauru');
insert into Pais (id, nome) values (170, 'Niue');
insert into Pais (id, nome) values (171, 'New Zealand');
insert into Pais (id, nome) values (172, 'Oman');
insert into Pais (id, nome) values (173, 'Panama');
insert into Pais (id, nome) values (174, 'Peru');
insert into Pais (id, nome) values (175, 'French Polynesia');
insert into Pais (id, nome) values (176, 'Papua New Guinea');
insert into Pais (id, nome) values (177, 'Philippines');
insert into Pais (id, nome) values (178, 'Pakistan');
insert into Pais (id, nome) values (179, 'Poland');
insert into Pais (id, nome) values (180, 'St. Pierre and Miquelon');
insert into Pais (id, nome) values (181, 'Pitcairn');
insert into Pais (id, nome) values (182, 'Puerto Rico');
insert into Pais (id, nome) values (183, 'State of Palestine');
insert into Pais (id, nome) values (184, 'Portugal');
insert into Pais (id, nome) values (185, 'Palau');
insert into Pais (id, nome) values (186, 'Paraguay');
insert into Pais (id, nome) values (187, 'Qatar');
insert into Pais (id, nome) values (188, 'Réunion');
insert into Pais (id, nome) values (189, 'Romania');
insert into Pais (id, nome) values (190, 'Serbia');
insert into Pais (id, nome) values (191, 'Russian Federation');
insert into Pais (id, nome) values (192, 'Rwanda');
insert into Pais (id, nome) values (193, 'Saudi Arabia');
insert into Pais (id, nome) values (194, 'Solomon Islands');
insert into Pais (id, nome) values (195, 'Seychelles');
insert into Pais (id, nome) values (196, 'Sudan');
insert into Pais (id, nome) values (197, 'Sweden');
insert into Pais (id, nome) values (198, 'Singapore');
insert into Pais (id, nome) values (199, 'Saint Helena');
insert into Pais (id, nome) values (200, 'Slovenia');
insert into Pais (id, nome) values (201, 'Svalbard and Jan Mayen Islands');
insert into Pais (id, nome) values (202, 'Slovakia');
insert into Pais (id, nome) values (203, 'Sierra Leone');
insert into Pais (id, nome) values (204, 'San Marino');
insert into Pais (id, nome) values (205, 'Senegal');
insert into Pais (id, nome) values (206, 'Somalia');
insert into Pais (id, nome) values (207, 'Suriname');
insert into Pais (id, nome) values (208, 'South Sudan');
insert into Pais (id, nome) values (209, 'Sao Tome and Principe');
insert into Pais (id, nome) values (210, 'El Salvador');
insert into Pais (id, nome) values (211, 'Sint Maarten');
insert into Pais (id, nome) values (212, 'Syria');
insert into Pais (id, nome) values (213, 'Swaziland');
insert into Pais (id, nome) values (214, 'Turks and Caicos Islands');
insert into Pais (id, nome) values (215, 'Chad');
insert into Pais (id, nome) values (216, 'French Southern Territories');
insert into Pais (id, nome) values (217, 'Togo');
insert into Pais (id, nome) values (218, 'Thailand');
insert into Pais (id, nome) values (219, 'Tajikistan');
insert into Pais (id, nome) values (220, 'Tokelau');
insert into Pais (id, nome) values (221, 'Timor-Leste');
insert into Pais (id, nome) values (222, 'Turkmenistan');
insert into Pais (id, nome) values (223, 'Tunisia');
insert into Pais (id, nome) values (224, 'Tonga');
insert into Pais (id, nome) values (225, 'Turkey');
insert into Pais (id, nome) values (226, 'Trinidad and Tobago');
insert into Pais (id, nome) values (227, 'Tuvalu');
insert into Pais (id, nome) values (228, 'Taiwan');
insert into Pais (id, nome) values (229, 'Tanzania');
insert into Pais (id, nome) values (230, 'Ukraine');
insert into Pais (id, nome) values (231, 'Uganda');
insert into Pais (id, nome) values (232, 'United States Minor Outlying Islands');
insert into Pais (id, nome) values (233, 'United States');
insert into Pais (id, nome) values (234, 'Uruguay');
insert into Pais (id, nome) values (235, 'Uzbekistan');
insert into Pais (id, nome) values (236, 'Vatican');
insert into Pais (id, nome) values (237, 'Saint Vincent and the Grenadines');
insert into Pais (id, nome) values (238, 'Venezuela');
insert into Pais (id, nome) values (239, 'Virgin Islands (British)');
insert into Pais (id, nome) values (240, 'Virgin Islands (U.S.)');
insert into Pais (id, nome) values (241, 'Vietnam');
insert into Pais (id, nome) values (242, 'Vanuatu');
insert into Pais (id, nome) values (243, 'Wallis and Futuna Islands');
insert into Pais (id, nome) values (244, 'Samoa');
insert into Pais (id, nome) values (245, 'Yemen');
insert into Pais (id, nome) values (246, 'Mayotte');
insert into Pais (id, nome) values (247, 'South Africa');
insert into Pais (id, nome) values (248, 'Zambia');
insert into Pais (id, nome) values (249, 'Zimbabwe');
